# Generated by Django 4.1.9 on 2023-06-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZapNFixApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='component_id',
        ),
        migrations.AlterField(
            model_name='repair',
            name='status',
            field=models.CharField(default='Requested', max_length=50),
        ),
        migrations.AddField(
            model_name='problem',
            name='component_id',
            field=models.ManyToManyField(to='ZapNFixApp.component'),
        ),
    ]
