# Generated by Django 4.1.9 on 2023-06-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZapNFixApp', '0002_component_image_remove_problem_component_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='component_id',
        ),
        migrations.AddField(
            model_name='problem',
            name='component_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ZapNFixApp.component'),
        ),
    ]
